### PR TITLE
Adding touch screen support

### PR DESCRIPTION
**Pull request by stretch4x4**
Issue #19
An attempt at supporting touch screen events in a desktop environment

### CODE REVIEW

**Comment by stretch4x4** [comment]
I have done enough to get this working for our use case, however I am sure there are some bits that could be cleaned up going forward.

I have tested this on a 22" touchscreen in chrome on windows and also in firefox on the same machine.

I was having an issue with the overlay appearing when you begin your drag but then not moving until I lifted off the screen and then dragged, this seemed to be when the event was handed over from the document watcher to the overlay watcher. I got around this by shifting my event handler to the document rather than the overlay and cleaning up when the overlay was disposed. However this trick doesn't seem to work in firefox and the break is still there.

I am not familiar enough with touch events to know what exactly is causing this behaviour or how to fix it, I also don't think I will have time to investigate as we aren't currently targeting firefox and I suspect it will require changes in how the drag events are tracked.. However I am submitting the code in the hopes that it will help someone and possibly give a base point for someone to work on fixes.

Thanks

**Comment by IanYates** [comment]
Thanks for sharing @stretch4x4 :)  I know it's not necessarily fashionable, but are you on Windows 8.1, and if so, how does it work in IE 11?

**Comment by stretch4x4** [comment]
No worries @IanYates 
We did have a surface somewhere but it seems to be "missing" at the minute so no I don't have an easy way to test it right now. I do at home though so if you have an example I could drop the new js into I could give that a crack later, otherwise it will be a while until I have time to build something to test it with.

**Comment by IanYates** [comment]
That's fine - I'll be digging in to this sort of thing again in about a week's time.  I'll try to remember to post back here.

IIRC (from a couple of months ago) the drag/drop worked quite well in IE since it falls back to mouse events.  With MS Edge supporting touch events (and pointer events?) it'll be interesting to see how these sort of things interact with one another.

**Comment by stretch4x4** [comment]
Yeah I thought it might have just worked in chrome but it didn't seem to..
It might cause issues but hopefully not as I think there is code to stop the events bubbling up..

**Comment by sunesimonsen** [comment]
I cherry-picked the commit e6fae5de1fed9f8077aaf92ae9ef6880edeaae83 and changed the code to only start the drag after a long-tap; otherwise it will conflict with scrolling. The sortable and scroll on drag examples doesn't work for touch yet, but this is definitely better than nothing. Thank you so much for you contribution @stretch4x4

**Comment by stretch4x4** [comment]
@sunesimonsen No worries,

It is interesting that you say the scroll doesn't work for you because it does for me on windows 7 in chrome with a touch screen.. I wonder if it could be a coordinate issue?

I have also opened Issue #28 With the long-tap to drag, I like the idea but it has created an issue for me in firefox.

**Comment by sunesimonsen** [comment]
The problem is that it starts dragging right away, that means you can't scroll on top of draggable elements. We very much need scrolling to work on top of draggable elements - take for example a list of mails that you can scroll but where the mails would also be draggable.

**Comment by stretch4x4** [comment]
Sorry I should have been clearer I was interested that you said the scroll on drag didn't work..
It did with touch controls horizontally for me in chrome..

**Comment by sunesimonsen** [comment]
If the scroll starts on a draggable element, it will start dragging instead of scrolling.

**Pull request closed without merging**
